import { STORAGE_KEYS } from "@/constants/storage";

export const HIERARCHICAL_PIPELINES_KEY = STORAGE_KEYS.HIERARCHICAL_PIPELINES;
export const USER_PIPELINE_VISIBILITY_KEY = STORAGE_KEYS.USER_PIPELINE_VISIBILITY;
