import '../styles/globals.css';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import IdleTokenRefreshWrapper from "@/components/IdleTokenRefreshWrapper";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#e6f4f1] to-[#d0ebe3] font-poppins`}
      >
        {children}
        <IdleTokenRefreshWrapper />
      </body>
    </html>
  );
}
